scan_filter_chain:
- name: angle1_1
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -3.15
    upper_angle: -3.11
- name: angle1_2
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: 3.11
    upper_angle: 3.15

- name: angle2_1
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: 0
    upper_angle: 0.03
- name: angle2_2
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -0.03
    upper_angle: 0